# Generated by Django 4.2.2 on 2023-07-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_order_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
