# Generated by Django 4.2.2 on 2023-07-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_product_order_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='product',
        ),
    ]
