# Generated by Django 4.2.2 on 2023-07-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
    ]
