# Generated by Django 4.2.2 on 2023-07-20 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order_transaction_id_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
