# Generated by Django 4.2.2 on 2023-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
