# Generated by Django 4.2.2 on 2023-07-07 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0003_course_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
